AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Blog Management System - Lambda Functions with Alias

Parameters:
  Version:
    Type: String
    Default: "1.0.0"
    Description: The version number for this deployment

Globals:
  Function:
    Runtime: python3.11
    Tags:
      Version: !Ref Version
    Environment:
      Variables:
        VERSION: !Ref Version

Resources:
  # Lambda Layer for common utilities
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blog-common-layer
      Description: Common utilities for blog Lambda functions
      ContentUri: ./layers/common-layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  # API Gateway - 기존 설정 유지
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod  # 고정값 사용
      EndpointConfiguration:
        Type: REGIONAL
      OpenApiVersion: '2.0'
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # 관리자 로그인 함수
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "BlogAuth"
      Handler: app.lambda_handler
      CodeUri: ./auth
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:blog/config-*"
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/login
            Method: POST
        AuthOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/login
            Method: OPTIONS
  # 게시판 CRUD 함수
  BoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "BlogBoard"
      Handler: app.lambda_handler
      CodeUri: ./board
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: "blog-table"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:blog/config-*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/blog-table"
      Events:
        # 게시글 목록 조회 (공개)
        ListBoardApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board
            Method: GET
        # 최근 게시글 5개 조회 (공개)
        RecentBoardApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board/recent
            Method: GET
        # 게시글 상세 조회 (공개)
        GetBoardApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board/{boardId}
            Method: GET
        # 게시글 생성 (관리자 전용)
        CreateBoardApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board
            Method: POST
        # 게시글 수정 (관리자 전용)
        UpdateBoardApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board/{boardId}
            Method: PUT
        # 게시글 삭제 (관리자 전용)
        DeleteBoardApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board/{boardId}
            Method: DELETE
        # 이미지 업로드 (관리자 전용)
        UploadImageApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board/upload
            Method: POST
        # CORS 옵션
        BoardOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board
            Method: OPTIONS
        BoardItemOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board/{boardId}
            Method: OPTIONS
        UploadOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /board/upload
            Method: OPTIONS
  # 뉴스 CRUD 함수
  NewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "BlogNews"
      Handler: app.lambda_handler
      CodeUri: ./news
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: "blog-table"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:blog/config-*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/blog-table"
      Events:
        # 뉴스 목록 조회 (공개)
        ListNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news
            Method: GET
        # 뉴스 상세 조회 (공개)
        GetNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: GET
        # 뉴스 생성 (관리자 전용)
        CreateNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news
            Method: POST
        # 뉴스 수정 (관리자 전용)
        UpdateNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: PUT
        # 뉴스 삭제 (관리자 전용)
        DeleteNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: DELETE
        # CORS 옵션
        NewsOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news
            Method: OPTIONS
        NewsItemOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: OPTIONS

  # 갤러리 CRUD 함수
  GalleryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "BlogGallery"
      Handler: app.lambda_handler
      CodeUri: ./gallery
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: "blog-table"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:blog/config-*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/blog-table"
      Events:
        # 갤러리 목록 조회 (공개)
        ListGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery
            Method: GET
        # 갤러리 상세 조회 (공개)
        GetGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: GET
        # 갤러리 생성 (관리자 전용)
        CreateGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery
            Method: POST
        # 갤러리 수정 (관리자 전용)
        UpdateGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: PUT
        # 갤러리 삭제 (관리자 전용)
        DeleteGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: DELETE
        # CORS 옵션
        GalleryOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery
            Method: OPTIONS
        GalleryItemOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: OPTIONS


Outputs:
  # Lambda Function Names (for CI/CD)
  AuthFunctionName:
    Description: "Auth Lambda Function Name"
    Value: !Ref AuthFunction

  BoardFunctionName:
    Description: "Board Lambda Function Name"
    Value: !Ref BoardFunction

  NewsFunctionName:
    Description: "News Lambda Function Name"
    Value: !Ref NewsFunction

  GalleryFunctionName:
    Description: "Gallery Lambda Function Name"
    Value: !Ref GalleryFunction

  # API Gateway Information
  ApiGatewayId:
    Description: "API Gateway ID"
    Value: !Ref ApiGateway

  ApiGatewayURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  # API Endpoints
  AuthApiEndpoint:
    Description: "Auth API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/login"

  BoardApiEndpoint:
    Description: "Board API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/board"

  NewsApiEndpoint:
    Description: "News API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/news"

  GalleryApiEndpoint:
    Description: "Gallery API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/gallery"
