AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Blog Management System - Lambda Functions with Alias

Parameters:
  Version:
    Type: String
    Default: "1.0.0"
    Description: The version number for this deployment

Globals:
  Function:
    Runtime: python3.11
    Tags:
      Version: !Ref Version
    Environment:
      Variables:
        VERSION: !Ref Version
        STAGE: prod

Resources:
  # Lambda Layer for common utilities
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blog-common-layer
      Description: Common utilities for blog Lambda functions
      ContentUri: ./layers/common-layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  # API Gateway - 기존 설정 유지
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod  # 고정값 사용
      EndpointConfiguration:
        Type: REGIONAL
      OpenApiVersion: '2.0'
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # 관리자 로그인 함수
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "BlogAuth"
      Handler: app.lambda_handler
      CodeUri: ./auth
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref CommonLayer
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:blog/config/*"
      Events:
        LoginApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/login
            Method: POST
        AuthOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/login
            Method: OPTIONS
        # 토큰 검증 엔드포인트 추가
        ValidateTokenApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/validate
            Method: POST
        ValidateTokenOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /auth/validate
            Method: OPTIONS

  # 뉴스 CRUD 함수
  NewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "BlogNews"
      Handler: app.lambda_handler
      CodeUri: ./news
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: "blog-table"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:blog/config/*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/blog-table"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:GeneratePresignedUrl
              Resource: !Sub "arn:aws:s3:::your-bucket-name/*"
      Events:
        # 뉴스 목록 조회 (공개)
        ListNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news
            Method: GET
        # 최근 뉴스 조회 (공개)
        RecentNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/recent
            Method: GET
        # 뉴스 상세 조회 (공개)
        GetNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: GET
        # 뉴스 생성 (관리자 전용)
        CreateNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news
            Method: POST
        # 파일 업로드 URL 생성 (관리자 전용)
        NewsUploadUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/upload-url
            Method: POST
        # 뉴스 수정 (관리자 전용)
        UpdateNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: PUT
        # 뉴스 삭제 (관리자 전용)
        DeleteNewsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: DELETE
        # CORS 옵션
        NewsOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news
            Method: OPTIONS
        NewsUploadUrlOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/upload-url
            Method: OPTIONS
        NewsItemOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /news/{newsId}
            Method: OPTIONS

  # 갤러리 CRUD 함수
  GalleryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "BlogGallery"
      Handler: app.lambda_handler
      CodeUri: ./gallery
      Timeout: 30
      MemorySize: 256
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          TABLE_NAME: "blog-table"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:blog/config/*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/blog-table"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:GeneratePresignedUrl
              Resource: !Sub "arn:aws:s3:::your-bucket-name/*"
      Events:
        # 갤러리 목록 조회 (공개)
        ListGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery
            Method: GET
        # 최근 갤러리 조회 (공개)
        RecentGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/recent
            Method: GET
        # 갤러리 상세 조회 (공개)
        GetGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: GET
        # 갤러리 생성 (관리자 전용)
        CreateGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery
            Method: POST
        # 파일 업로드 URL 생성 (관리자 전용)
        GalleryUploadUrlApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/upload-url
            Method: POST
        # 갤러리 수정 (관리자 전용)
        UpdateGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: PUT
        # 갤러리 삭제 (관리자 전용)
        DeleteGalleryApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: DELETE
        # CORS 옵션
        GalleryOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery
            Method: OPTIONS
        GalleryUploadUrlOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/upload-url
            Method: OPTIONS
        GalleryItemOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gallery/{galleryId}
            Method: OPTIONS


Outputs:
  # Lambda Function Names (for CI/CD)
  AuthFunctionName:
    Description: "Auth Lambda Function Name"
    Value: !Ref AuthFunction

  NewsFunctionName:
    Description: "News Lambda Function Name"
    Value: !Ref NewsFunction

  GalleryFunctionName:
    Description: "Gallery Lambda Function Name"
    Value: !Ref GalleryFunction

  # API Gateway Information
  ApiGatewayId:
    Description: "API Gateway ID"
    Value: !Ref ApiGateway

  ApiGatewayURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  # API Endpoints
  AuthApiEndpoint:
    Description: "Auth API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/login"

  NewsApiEndpoint:
    Description: "News API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/news"

  GalleryApiEndpoint:
    Description: "Gallery API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/gallery"
