AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple API Gateway + Lambda example with Python

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: The deployment stage (dev, prod)
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Tags:
      Environment: !Ref Stage

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      EndpointConfiguration:
        Type: REGIONAL
      OpenApiVersion: '2.0'
      Tags:
        Environment: !Ref Stage

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "HelloFunction-${Stage}"
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: ./hello
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes
        Alarms:
          - !Ref AliasErrorMetricGreaterThanZeroAlarm
          - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
      Events:
        HelloApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /hello
            Method: GET

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "UsersFunction-${Stage}"
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: ./users
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Canary10Percent10Minutes
        Alarms:
          - !Ref UsersAliasErrorAlarm
          - !Ref UsersLatestVersionErrorAlarm
      Events:
        GetUserApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users/{userId}
            Method: GET
        ListUsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users
            Method: GET

  AliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${HelloFunction}:live"
        - Name: FunctionName
          Value: !Sub "HelloFunction-${Stage}"
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${HelloFunction}:live"
        - Name: FunctionName
          Value: !Sub "HelloFunction-${Stage}"
        - Name: ExecutedVersion
          Value: !GetAtt HelloFunction.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  UsersAliasErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Users Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${UsersFunction}:live"
        - Name: FunctionName
          Value: !Sub "UsersFunction-${Stage}"
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  UsersLatestVersionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Users Function Latest Version Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${UsersFunction}:live"
        - Name: FunctionName
          Value: !Sub "UsersFunction-${Stage}"
        - Name: ExecutedVersion
          Value: !GetAtt UsersFunction.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

Outputs:
  HelloFunction:
    Description: "Hello Lambda Function ARN"
    Value: !GetAtt HelloFunction.Arn

  UsersFunction:
    Description: "Users Lambda Function ARN"
    Value: !GetAtt UsersFunction.Arn

  HelloApi:
    Description: "API Gateway endpoint URL for Hello function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/hello/"

  UsersApi:
    Description: "API Gateway endpoint URL for Users function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/users/"

  ApiGatewayURL:
    Description: "Base URL for API Gateway"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
