name: Deploy SAM Application

on:
  push:
    branches: [ main ]

permissions:
  id-token: write   # OIDC에 필요한 권한
  contents: read    # 코드 체크아웃에 필요한 권한

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aws-sam-cli
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Build SAM application
      run: sam build
    
    - name: Deploy SAM application
      run: |
        sam deploy --stack-name base-api-server \
          --s3-bucket ${{ secrets.S3_BUCKET }} \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset